name: NuGet Build

on:
  create:
    tags: 1.*
    branches-ignore: '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
          
    - name: Echo - Latest Version Tag
      id: latest_tag
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
    
    - name: Print
      run:
        echo $VERSION
      env:
        VERSION: ${{ steps.latest_tag.outputs.VERSION }}
