name: NuGet Build

on:
  create:
    tags: 1.*
    branches-ignore: '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
          
    - name: Echo - Latest Version Tag
      run: echo TAG=$TAG_VERSION
      env:
        TAG_VERSION: (git describe --tags $(git rev-list --tags --max-count=1))
