name: NuGet Build

on:
  create:
    tags: 1.*
    branches-ignore: '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
          
    - name: Echo - Latest Version Tag
      run: echo TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.200
    
    - name: Restore NuGet Packages
      run: dotnet restore
    
    - name: Build - Release
      run: dotnet build --configuration Release --no-restore
