name: NuGet Build

on:
  create:
    tags: 1.*
    branches-ignore: '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
          
    - name: Echo - Latest Version Tag
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
    
    - name: Print
      run: echo $VERSION
